version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: searty_user
      POSTGRES_PASSWORD: searty
      POSTGRES_DB: searty
volumes:
  postgres:
